Decouple # of worker threads from max concurrency
shadow/shadow pull request #1238
Opened 2021-03-30 19:02 UTC by sporksmith

1. Adds a WorkerPool with a callback-style interface instead of having a
   series of coordinated barriers.

2. Adds a --max-concurrency option that allows us to restrict the number
   of workers that can run concurrently. The WorkerPool also implements
   "worker stealing" to try to keep all --max-concurrency CPUs utilized.
   e.g. setting the # of workers to the # of hosts, max concurrency to
   the number of CPUs, and using the "host" scheduler is somewhat analagous
   to using the work-stealing scheduler.

These changes are intended primarily for the dev/phantom branch, since
ptrace has better performance with a smaller number of tracees per
thread. We're including it here in main for apples-to-apples performance
comparison between the shadow 'classic' and 'phantom' architectures.

Originally I tried to keep 1. as a separate commit from 2., but after a
series of fixup commits 1. and 2. got too tangled together.

2021-03-30 23:49 UTC, sporksmith commented
I haven't debugged the deadlock at end of simulation yet, but based on the stacks you sent it looks like a bug in process or ptrace_thread. Did you ever get to the end of a simulation without (the earlier version of) this PR?

As I was cleaning up comments, it occurred to me that something like "vCpu" would be a bit less unwieldy than "concurrency index". Otoh one might take the name to mean something like a "shadow CPU". Wdyt?

As I was looking a bit more at the "gather info" step where we find the time for the next round, I realized it's almost entirely serialized on the global mutex anyway. We could probably just change the scheduler-policy-callback that currently gives the min time for a single worker to instead iterate over its per-worker data structures and return the global minimum time, and just call that directly from the "main" thread in between rounds. Left it alone for now, though.

2021-03-31 16:09 UTC, sporksmith commented
Did some ad-hoc testing and ran into a problem with pthread_setaffinity_np I couldn't figure out. (It kept returning EFAULT, but I verified several ways that the address being passed was valid).

Pushed a fixup to remove the new pthread-based affinity API I'd added and instead use the existing api to set it via tid.

In some ad-hoc testing on a balanced workload, it seems to be slightly faster with the new scheduler in general.

On current `main`, with work-stealing:

```
$ time ~/.shadow/bin/shadow --pin-cpus -w 4 ./config.xml > shadow.log
** Starting Shadow v1.13.2-692-g12117c17 2021-03-30--09:30:08 with GLib v2.56.4 and IGraph v0.7.1
** Stopping Shadow, returning code 0 (success)

real	0m13.400s
user	0m40.652s
sys	0m11.434s
```

On current `main`, with host scheduler:

```
$ time ~/.shadow/bin/shadow --pin-cpus -w 4 -t host ./config.xml > shadow.log
** Starting Shadow v1.13.2-692-g12117c17 2021-03-30--09:30:08 with GLib v2.56.4 and IGraph v0.7.1
** Stopping Shadow, returning code 0 (success)

real	0m12.943s
user	0m37.753s
sys	0m11.556s
```

This PR with work-stealing:

```
$ time ~/.shadow/bin/shadow --pin-cpus -w 4 ./config.xml > shadow.log
** Starting Shadow v1.13.2-694-gb3b86509 2021-03-31--10:47:44 with GLib v2.56.4 and IGraph v0.7.1
** Stopping Shadow, returning code 0 (success)

real	0m12.943s
user	0m39.014s
sys	0m11.238s
```

This PR with host scheduler:

```
$ time ~/.shadow/bin/shadow --pin-cpus -w 4 -t host ./config.xml > shadow.log
** Starting Shadow v1.13.2-694-gb3b86509 2021-03-31--10:47:44 with GLib v2.56.4 and IGraph v0.7.1
** Stopping Shadow, returning code 0 (success)

real	0m12.519s
user	0m36.446s
sys	0m11.343s
```

This PR with host scheduler and 1 host/worker:

```
$ time ~/.shadow/bin/shadow --pin-cpus -w 256 --max-concurrency=4 -t host ./config.xml > shadow.log
** Starting Shadow v1.13.2-694-gb3b86509 2021-03-31--10:47:44 with GLib v2.56.4 and IGraph v0.7.1
** Stopping Shadow, returning code 0 (success)

real	0m13.103s
user	0m37.678s
sys	0m13.259s
```

2021-03-31 17:06 UTC, sporksmith commented
Reproduced the tor deadlock on `dev` and am debugging now. (i.e. confirmed unrelated to this PR)

2021-03-31 17:22 UTC, sporksmith commented
> Reproduced the tor deadlock on dev and am debugging now. (i.e. confirmed unrelated to this PR)

Oops, built but didn't install. So far *haven't* reproduced the deadlock on dev. Still digging...

2021-03-31 22:02 UTC, robgjansen requested changes
Sorry, this is difficult to review and took me a while. I still don't think I understand everything, especially with respect to how CPU affinity is being managed across workers (pthreads) and concurrency queues (logical processors). I'm sending this feedback now so I don't hold you up any longer, and then I can review again.

> Did you ever get to the end of a simulation without (the earlier version of) this PR?

Yes, my experiments complete using phantom without the earlier max-concurrency PR.

> As I was cleaning up comments, it occurred to me that something like "vCpu" would be a bit less unwieldy than "concurrency index". Otoh one might take the name to mean something like a "shadow CPU". Wdyt?

Yes, I think the concurrency queue thing might be something holding me up. I can see how vCpu might be misinterpreted too. I suggest we use `logical processor` to refer to these "concurrency queues". A processor isn't quite the same as a cpu, but also implies that it could be run on different physical cores, which is how they work. A `logical processor` could be shortened to `log_proc` or `lp`, and then each worker has an `assigned_lp_id`. This change would require a bit of renaming, but worth it I think.

> the "gather info" step

I think we should just implement the suggestion you made (to do it during the round), which I outlined more fully in a comment below, and then remove the "gather info" step. It seems almost trivial to implement.

2021-04-01 23:20 UTC, sporksmith commented on src/main/core/worker.h
> +pthread_t workerpool_getThread(WorkerPool* pool, int threadId);
I ended up creating a LogicalProcessor object and breaking that into its own module. IMO the WorkerPool is too coupled with Worker to be worth breaking out.

2021-04-01 23:20 UTC, sporksmith commented on src/main/core/scheduler/scheduler.c
> +                workeri++ % workerpool_getNWorkers(scheduler->workerPool));
Done

2021-04-01 23:21 UTC, sporksmith commented on src/main/core/scheduler/scheduler.c
> +                           _scheduler_collectInfoWorkerTask, scheduler);
Agreed that we should do it, and tempting to fold it into this PR, but given this is already a pretty big change I think it'd be better to break into its own.

2021-04-01 23:21 UTC, sporksmith commented on src/main/core/worker.c
> +    int concurrencyIdx;
Done

2021-04-01 23:21 UTC, sporksmith commented on src/main/core/worker.c
> +    GMutex* qMutexes;
Hopefully clearer now

2021-04-01 23:21 UTC, sporksmith commented on src/main/core/worker.c
> +    int* cpuIds;
done

2021-04-01 23:28 UTC, sporksmith commented on src/main/core/worker.c
> +        int idx = (concurrencyIdx + i) % pool->nConcurrent;
Done. It prefers a worker that last ran on the current logical processor. After that the order is somewhat arbitrary.

2021-04-01 23:29 UTC, sporksmith commented on src/main/core/worker.c
> +            workerPool, worker->concurrencyIdx);
The former. Renamed _workerpool_getNextWorkerForConcurrencyIdx.

2021-04-01 23:30 UTC, sporksmith commented on src/main/core/worker.c
> +    }
Right. Added a comment.

2021-04-01 23:45 UTC, sporksmith commented
Oops - need to merge and resolve conflicts. Marked unready again :)

2021-04-02 00:06 UTC, sporksmith commented
*Now* ready again

2021-04-02 02:08 UTC, robgjansen approved these changes
Looks great! The LogicalProcessor module is a big improvement. Thanks for your hard work on the design and on cleaning this up!

2021-04-02 02:08 UTC, robgjansen commented on src/main/core/scheduler/scheduler.c
> +                      "--max-concurrency > -w");
Nit: `-w` --> `--workers`

2021-04-02 05:07 UTC, merged