setup: Support --compile-commands in incremental builds
shadow/shadow pull request #2495
Opened 2022-10-27 17:58 UTC by sporksmith

Use `bear`'s `--append` flag to update an existing `compile_commands.json`, so that we can run it on incremental builds as well without erasing entries for files that weren't rebuilt.

2022-10-27 18:07 UTC, sporksmith commented
Maybe we should get rid of the `setup` flag altogether, and just do it automatically if we can find the `bear` executable, and maybe log a warning if we can't?

2022-10-28 02:35 UTC, robgjansen requested changes
> Maybe we should get rid of the setup flag altogether, and just do it automatically if we can find the bear executable, and maybe log a warning if we can't?

+1 I prefer this simpler approach without the setup flag.

It would be nice to log if bear isn't installed in any case, but I wonder if we ought to make it less severe than warn since most people using Shadow probably don't need or want bear?

2022-10-28 16:11 UTC, sporksmith commented
Done. I didn't add a new log line, since we already log the `make` command-line and can see whether or not it used `bear`

2022-10-28 19:24 UTC, robgjansen approved these changes

2022-10-28 22:14 UTC, merged