Make `ForeignPtr` `Send` and `Sync`
shadow/shadow pull request #2902
Opened 2023-05-03 17:47 UTC by stevenengler

This also:

- makes `PhantomData<T>` `VirtualAddressSpaceIndependent` for all `T`
- adds inlining to methods of `ForeignPtr`, `SysCallReg`, and `SysCallArgs` since these methods are very small functions around integer operations.

2023-05-03 19:00 UTC, sporksmith requested changes

2023-05-10 02:56 UTC, sporksmith commented on src/lib/vasi/src/lib.rs
> +unsafe impl<T> VirtualAddressSpaceIndependent for core::marker::PhantomData<T> {}
ah we do have this - the attribute is `unsafe_assume_virtual_address_space_independent`. Example: https://github.com/shadow/shadow/blob/36a121222136f6fa0d9a3006c7ad3b3ca42c5aae/src/lib/shadow-shim-helper-rs/src/signals.rs#L192

2023-05-15 21:33 UTC, stevenengler commented on src/lib/vasi/src/lib.rs
> +unsafe impl<T> VirtualAddressSpaceIndependent for core::marker::PhantomData<T> {}
Reverted the `PhantomData` commit and added `#[unsafe_assume_virtual_address_space_independent]`.

2023-05-15 21:36 UTC, sporksmith approved these changes

2023-05-15 22:24 UTC, merged